In [1]:
#-*- coding: utf-8 -*-
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
# seed 값 설정 

seed = 42
np.random.seed(seed)
tf.random.set_seed(42)


In [4]:
pd.read_csv('/content/drive/MyDrive/dataset/housing.csv', delim_whitespace= True, header=None)
# delim_whitespace= True : 공백이 많은 데이터 일때에 공백을 지워주는 함수

0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

In [5]:
df = pd.read_csv('/content/drive/MyDrive/dataset/housing.csv', delim_whitespace= True, header=None)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       506 non-null    float64
 1   1       506 non-null    float64
 2   2       506 non-null    float64
 3   3       506 non-null    int64  
 4   4       506 non-null    float64
 5   5       506 non-null    float64
 6   6       506 non-null    float64
 7   7       506 non-null    float64
 8   8       506 non-null    int64  
 9   9       506 non-null    float64
 10  10      506 non-null    float64
 11  11      506 non-null    float64
 12  12      506 non-null    float64
 13  13      506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [7]:
df.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [8]:
dataset = df.values
x = dataset[:,:-1 ]
y = dataset[:,-1 ]

In [15]:
x.shape

(506, 13)

In [13]:
x_train, x_test, y_train, y_test = \
      train_test_split(x,y,test_size=0.3,random_state=seed)

In [16]:
# 모델 생성
model = Sequential()
model.add(Dense(30, input_dim=13, activation ='relu'))
model.add(Dense(6, activation ='relu'))
model.add(Dense(1)) # 활성화 함수 없음 (회귀 : 예측)

In [17]:
# 환경설정
model.compile(loss='mean_squared_error',
              optimizer = 'adam')

In [18]:
# 모델학습
model.fit(x_train,y_train, epochs=200, batch_size=10)

Epoch 1/200
36/36 [==============================] - 4s 7ms/step - loss: 337.6849
Epoch 2/200
36/36 [==============================] - 0s 6ms/step - loss: 150.7196
Epoch 3/200
36/36 [==============================] - 0s 6ms/step - loss: 102.7468
Epoch 4/200
36/36 [==============================] - 0s 7ms/step - loss: 85.5121
Epoch 5/200
36/36 [==============================] - 0s 7ms/step - loss: 79.3276
Epoch 6/200
36/36 [==============================] - 0s 6ms/step - loss: 71.9457
Epoch 7/200
36/36 [==============================] - 0s 6ms/step - loss: 71.7131
Epoch 8/200
36/36 [==============================] - 0s 6ms/step - loss: 68.8092
Epoch 9/200
36/36 [==============================] - 0s 6ms/step - loss: 69.5986
Epoch 10/200
36/36 [==============================] - 0s 6ms/step - loss: 64.0768
Epoch 11/200
36/36 [==============================] - 0s 6ms/step - loss: 66.8733
Epoch 12/200
36/36 [==============================] - 0s 6ms/step - loss: 65.1563
Epoch 13/200
36/36 [==

In [19]:
# 예측값과 실제값 비교

model.predict(x_test)

array([[28.853884 ],
       [40.274616 ],
       [19.63702  ],
       [27.317139 ],
       [18.613983 ],
       [21.109896 ],
       [17.284727 ],
       [16.97046  ],
       [24.04139  ],
       [22.638693 ],
       [22.407717 ],
       [18.69781  ],
       [-0.7188932],
       [21.914886 ],
       [21.051722 ],
       [25.099833 ],
       [18.732538 ],
       [ 8.620901 ],
       [42.719166 ],
       [18.339985 ],
       [32.36008  ],
       [32.21604  ],
       [13.437585 ],
       [24.123533 ],
       [21.648804 ],
       [17.068546 ],
       [26.474987 ],
       [18.551369 ],
       [20.197132 ],
       [22.424175 ],
       [22.449945 ],
       [27.634813 ],
       [25.259357 ],
       [27.569586 ],
       [16.212484 ],
       [18.420977 ],
       [33.70656  ],
       [26.228163 ],
       [21.654724 ],
       [24.89039  ],
       [15.5467005],
       [39.170982 ],
       [45.440735 ],
       [20.875084 ],
       [27.43709  ],
       [19.217697 ],
       [15.227417 ],
       [26.28

In [21]:
model.predict(x_test).flatten()

array([28.853884 , 40.274616 , 19.63702  , 27.317139 , 18.613983 ,
       21.109896 , 17.284727 , 16.97046  , 24.04139  , 22.638693 ,
       22.407717 , 18.69781  , -0.7188932, 21.914886 , 21.051722 ,
       25.099833 , 18.732538 ,  8.620901 , 42.719166 , 18.339985 ,
       32.36008  , 32.21604  , 13.437585 , 24.123533 , 21.648804 ,
       17.068546 , 26.474987 , 18.551369 , 20.197132 , 22.424175 ,
       22.449945 , 27.634813 , 25.259357 , 27.569586 , 16.212484 ,
       18.420977 , 33.70656  , 26.228163 , 21.654724 , 24.89039  ,
       15.5467005, 39.170982 , 45.440735 , 20.875084 , 27.43709  ,
       19.217697 , 15.227417 , 26.280298 , 19.999105 , 32.93045  ,
       22.936943 , 39.985573 , 16.866938 , 28.46006  , 43.051376 ,
       24.177568 , 20.87728  , 38.13453  , 26.40418  , 15.258229 ,
       24.042374 , 36.363174 , 33.932907 , 12.1603985, 24.596043 ,
       18.222958 , 20.002327 , 28.45153  , 35.47066  , 17.211552 ,
       19.829906 , 30.296516 , 15.550631 , 23.44858  , 24.8542

In [22]:
y_test # 실제값

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,
        8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8, 13.9, 21.8, 23.7, 17.6,
       24.4,  8.8, 19.2, 25.3, 20.4, 23.1, 37.9, 15.6, 45.4, 15.7, 22.6,
       14.5, 18.7, 17.8, 16.1, 20.6, 31.6, 29.1, 15.6, 17.5, 22.5, 19.4,
       19.3,  8.5, 20.6, 17. , 17.1, 14.5, 50. , 14

In [24]:
y_pred = model.predict(x_test).flatten() # .flatten() 실제값과 같은 차원으로 맞춰주기위해 사용
y_pred # 예측값

array([28.853884 , 40.274616 , 19.63702  , 27.317139 , 18.613983 ,
       21.109896 , 17.284727 , 16.97046  , 24.04139  , 22.638693 ,
       22.407717 , 18.69781  , -0.7188932, 21.914886 , 21.051722 ,
       25.099833 , 18.732538 ,  8.620901 , 42.719166 , 18.339985 ,
       32.36008  , 32.21604  , 13.437585 , 24.123533 , 21.648804 ,
       17.068546 , 26.474987 , 18.551369 , 20.197132 , 22.424175 ,
       22.449945 , 27.634813 , 25.259357 , 27.569586 , 16.212484 ,
       18.420977 , 33.70656  , 26.228163 , 21.654724 , 24.89039  ,
       15.5467005, 39.170982 , 45.440735 , 20.875084 , 27.43709  ,
       19.217697 , 15.227417 , 26.280298 , 19.999105 , 32.93045  ,
       22.936943 , 39.985573 , 16.866938 , 28.46006  , 43.051376 ,
       24.177568 , 20.87728  , 38.13453  , 26.40418  , 15.258229 ,
       24.042374 , 36.363174 , 33.932907 , 12.1603985, 24.596043 ,
       18.222958 , 20.002327 , 28.45153  , 35.47066  , 17.211552 ,
       19.829906 , 30.296516 , 15.550631 , 23.44858  , 24.8542

In [25]:
y_pred = model.predict(x_test).flatten()

for i in range(10):
  label = y_test[i]
  prediction = y_pred[i]

  print("실제가격: {:.3f},예상가격:{:.3f}".format(label, prediction))

실제가격: 23.600,예상가격:28.854
실제가격: 32.400,예상가격:40.275
실제가격: 13.600,예상가격:19.637
실제가격: 22.800,예상가격:27.317
실제가격: 16.100,예상가격:18.614
실제가격: 20.000,예상가격:21.110
실제가격: 17.800,예상가격:17.285
실제가격: 14.000,예상가격:16.970
실제가격: 19.600,예상가격:24.041
실제가격: 16.800,예상가격:22.639
