In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
import tensorflow as tf


In [6]:
# seed 값 설정

np.random.seed(42)
tf.random.set_seed(42)

In [7]:
# 데이터 입력
pd.read_csv('/content/drive/MyDrive/dataset/iris.csv',
            names = ['sepal_length', 'sepal_width','petal_length','species'])

sepal_length  sepal_width  petal_length         species
5.1           3.5          1.4           0.2     Iris-setosa
4.9           3.0          1.4           0.2     Iris-setosa
4.7           3.2          1.3           0.2     Iris-setosa
4.6           3.1          1.5           0.2     Iris-setosa
5.0           3.6          1.4           0.2     Iris-setosa
..            ...          ...           ...             ...
6.7           3.0          5.2           2.3  Iris-virginica
6.3           2.5          5.0           1.9  Iris-virginica
6.5           3.0          5.2           2.0  Iris-virginica
6.2           3.4          5.4           2.3  Iris-virginica
5.9           3.0          5.1           1.8  Iris-virginica

[150 rows x 4 columns]

In [8]:
df = pd.read_csv('/content/drive/MyDrive/dataset/iris.csv',
            names = ['sepal_length', 'sepal_width','petal_length','species'])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 150 entries, 5.1 to 5.9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   species       150 non-null    object 
dtypes: float64(3), object(1)
memory usage: 5.9+ KB


In [11]:
# 데이터 분류
df.values

array([[3.5, 1.4, 0.2, 'Iris-setosa'],
       [3.0, 1.4, 0.2, 'Iris-setosa'],
       [3.2, 1.3, 0.2, 'Iris-setosa'],
       [3.1, 1.5, 0.2, 'Iris-setosa'],
       [3.6, 1.4, 0.2, 'Iris-setosa'],
       [3.9, 1.7, 0.4, 'Iris-setosa'],
       [3.4, 1.4, 0.3, 'Iris-setosa'],
       [3.4, 1.5, 0.2, 'Iris-setosa'],
       [2.9, 1.4, 0.2, 'Iris-setosa'],
       [3.1, 1.5, 0.1, 'Iris-setosa'],
       [3.7, 1.5, 0.2, 'Iris-setosa'],
       [3.4, 1.6, 0.2, 'Iris-setosa'],
       [3.0, 1.4, 0.1, 'Iris-setosa'],
       [3.0, 1.1, 0.1, 'Iris-setosa'],
       [4.0, 1.2, 0.2, 'Iris-setosa'],
       [4.4, 1.5, 0.4, 'Iris-setosa'],
       [3.9, 1.3, 0.4, 'Iris-setosa'],
       [3.5, 1.4, 0.3, 'Iris-setosa'],
       [3.8, 1.7, 0.3, 'Iris-setosa'],
       [3.8, 1.5, 0.3, 'Iris-setosa'],
       [3.4, 1.7, 0.2, 'Iris-setosa'],
       [3.7, 1.5, 0.4, 'Iris-setosa'],
       [3.6, 1.0, 0.2, 'Iris-setosa'],
       [3.3, 1.7, 0.5, 'Iris-setosa'],
       [3.4, 1.9, 0.2, 'Iris-setosa'],
       [3.0, 1.6, 0.2, 'I

In [21]:
dataset = df.values

x = dataset[:,:-1].astype(float)
y_obj= dataset[:, -1] # y값이 문자열(object)

In [22]:
# 문자열 >> 숫자 변환 (label_encoder 사용)

le=LabelEncoder()
le.fit(y_obj)
y = le.transform(y_obj)

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
tf.keras.utils.to_categorical(y)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [25]:
y_encoded= tf.keras.utils.to_categorical(y)
# 활성화 함수 적용하기 위해서 y 값을 0, 1로 변경 (one_hot encoding)

In [26]:
# 모델 설정
model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu'))
model.add(Dense((3), activation='softmax'))

In [31]:
# 모델 컴파일
model.compile(loss='categorical_crossentropy', # 범주형 크로스엔트로피 사용(일반적)
              optimazer = 'adam',              # 최적화 함수 : adam
              metrics =['accuracy'])           # 평가기준 : accuracy (정확도)

TypeError: ignored

In [28]:
# 모델 실행
model.fit(x, y_encoded, epochs =50, batch_size=1)

RuntimeError: ignored

In [29]:
# 결과 출력
print('\n Accuracy : %.4f'%(model.evaluate(x,y_encoded)[1]))

RuntimeError: ignored

In [ ]:
# 그래프로 확인 
sns.pairplot(df, hue='species')
plt.show()

In [ ]:
/content/drive/MyDrive/dataset/iris.csv